### ISSUE TITLE
HSTS error when attempting password reset

### ISSUE THREAD

**Issue by grahamalama** [toddbirchard/ghosttheme-stockholm#236]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/20747904/47684765-63cb6f00-dbaa-11e8-8788-c6c2dfc12fd7.png">

Just tried to do a password reset, and Firefox sent back this error.

**Comment by toddbirchard** [comment]
@grahamalama I just noticed I left this unanswered for 2 years! 🥺 Is this still an issue?
