### ISSUE TITLE
series: Page containing all posts of a series, compiled via dynamic routing.

### ISSUE THREAD

**Issue by 84896150** [toddbirchard/ghosttheme-stockholm#526]
series: Page containing all posts of a series, compiled via dynamic routing.
Can you say how to use it?

**Comment by toddbirchard** [comment]
Hi @84896150,

This feature uses Ghost's _dynamic routing_ feature. Specifically, it works by using _collections_. A tutorial on how to use Ghost's collections can be found [here](https://docs.ghost.org/tutorials/building-a-content-hub/).

I've uploaded my [routes.yaml](https://hackers.nyc3.digitaloceanspaces.com/yaml/routes.yaml) file as an example of how this works on [hackers and slackers](https://hackersandslackers.com). In short, I'm using "internal tags" to separate posts into series'. When modifying routes.yaml, remember the following:

- **/link-name-example/**: The url which the page will live.
- **controller**: (Set this to true).
- **template**: The name of the template (aka _series.hbs_) which will be used to render the page.
- **filter**: Filters to specify which posts to show.

Let me know if you have any questions!
