### ISSUE TITLE
I added the series page，But when I open the page，Nothing to show

### ISSUE THREAD

**Issue by 84896150** [toddbirchard/ghosttheme-stockholm#527]
I added the series page，But when I open the page，Nothing to show

**Comment by toddbirchard** [comment]
@84896150 Do you have a copy for your routes.yaml file available so I can assist in debugging?

**Comment by 84896150** [comment]
routes:
  /series/code-snippet-corner/:
    controller: channel
    template: series
    order: asc
    filter: tag:[code-snippet-corner]
  /series/hacking-tableau-server/:
    controller: channel
    template: series
    order: asc
    filter: tag:[hacking-tableau-server]
  /series/create-an-aws-api/:
    controller: channel
    template: series
    order: asc
    filter: tag:[create-an-aws-api]
  /series/working-with-mysql/:
    controller: channel
    template: series
    order: asc
    filter: tag:[working-with-mysql]
  /series/data-analysis-pandas/:
    controller: channel
    template: series
    filter: tag:[data-analysis-pandas]
    include: count.posts,authors,tags
  /series/building-flask-apps/:
    controller: channel
    template: series
    order: asc
    filter: tag:[building-flask-apps]
  /series/adventures-in-excel/:
    controller: channel
    template: series
    order: asc
    filter: tag:[adventures-in-excel]
  /series/the-rise-of-google-cloud/:
    controller: channel
    template: series
    order: asc
    filter: tag:[the-rise-of-google-cloud]
  /series/mongodb-cloud/:
    controller: channel
    template: series
    order: asc
    filter: tag:[mongodb-cloud]
  /series/starting-django/:
    controller: channel
    template: series
    order: asc
    filter: tag:[starting-django]
  /series/mapping-data-with-mapbox/:
    controller: channel
    template: series
    order: asc
    filter: tag:[mapping-data-with-mapbox]
  /series/plotly-dash/:
    controller: channel
    template: series
    order: asc
    filter: tag:[plotly-dash]
  /series/welcome-to-sql/:
    controller: channel
    template: series
    order: asc
    filter: tag:[welcome-to-sql]
  /series/graphql-hype/:
    controller: channel
    template: series
    order: asc
    filter: tag:[graphql-hype]
  /archive/:
    controller: channel
    template: postarchive
    order: desc

collections:
  /:
    permalink: /{slug}/
    template:
      - index
  /callbacks/medium/: # index URL
    permalink: /medium/

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

**Comment by 84896150** [comment]
Version 2.19.4
Environment production
Database mysql
Mail Direct

**Comment by 84896150** [comment]
![image](https://user-images.githubusercontent.com/3245204/55863484-3220f000-5bad-11e9-9897-176bb2f8ff12.png)
https://www.docs.wang/series/

**Comment by toddbirchard** [comment]
@84896150 here's where you can find **routes.yaml** if you're having trouble: https://i.imgur.com/tOauKQo.png
