### ISSUE TITLE
Thanks for the theme!

### ISSUE THREAD

**Issue by witnessmenow** [toddbirchard/ghosttheme-stockholm#85]
Just wanted to say thanks for the theme and I didn't see any other way of contacting you.

By far the nicest free theme for ghost that I came across.

I'm using it with some very minor modifications here:
http://blough.ie/

**Comment by toddbirchard** [comment]
Best GitHub issue I’ve ever received! Happy to have been able to help :).

There are a lot of tweaks and improvements coming down the line. Stay in touch!
